Add Node Module BOM CNB to order groupings
paketo-buildpacks/nodejs pull request #440
Opened 2021-08-24 19:43 UTC by sophiewigmore

## Summary

Resolves #438 

## Use Cases

Allows users to get Bill of Materials entries for node modules when they run `pack inspect-image <app-image> --bom`

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2021-08-24 20:49 UTC, arjun024 requested changes

2021-08-24 20:49 UTC, arjun024 commented on buildpack.toml
> +
This is repeated

2021-08-24 21:20 UTC, sophiewigmore commented on buildpack.toml
> +
thanks, fixed it

2021-08-24 21:46 UTC, arjun024 approved these changes

2021-08-25 14:14 UTC, thitch97 approved these changes

2021-08-25 14:14 UTC, merged